# spring.application.name=qna
# resources/application.yml
# H2 DB? ??? ??? ?? ??
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# H2 ??????? ????? ?? ?????? ???? ??
datasource:
  url: jdbc:h2:mem:qna;NON_KEYWORDS=USER
  username: sa
  password:
  driver-class-name: org.h2.Driver